### PR TITLE
upgrade x/net to 0.17.0

### PR DESCRIPTION
**Pull request by sseago**

### CODE REVIEW

**Comment by jmontleon** [comment]
Same question as https://github.com/migtools/mig-controller/pull/1356#issuecomment-1762148448

**Comment by sseago** [comment]
@jmontleon I thought we'd determined that go.sum doesn't matter. Only what's in go.mod is relevant to the packages actually included in the build.

**Review by weshayutin — APPROVED** [review]

**Comment by jmontleon** [comment]
> @jmontleon I thought we'd determined that go.sum doesn't matter. Only what's in go.mod is relevant to the packages actually included in the build.

We did. Added some info on the other issue: https://github.com/migtools/mig-controller/pull/1356#issuecomment-1766716309

**Pull request merged**
